function Gamma = Gamma_fun(du1,m,u1,x7,x8,x9,x10,x11,x12)
%Gamma_fun
%    Gamma = Gamma_fun(DU1,M,U1,X7,X8,X9,X10,X11,X12)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Sep-2022 09:10:44

t2 = cos(x7);
t3 = cos(x8);
t4 = cos(x9);
t5 = sin(x7);
t6 = sin(x8);
t7 = sin(x9);
t12 = 1.0./m;
t8 = t4.*x10;
t9 = t4.*x11;
t10 = t7.*x10;
t11 = t7.*x11;
t13 = -t11;
t14 = t9+t10;
t15 = t8+t13;
t16 = t2.*t3.*t12.*t14.*u1;
t17 = t3.*t5.*t12.*t14.*u1;
t18 = t2.*t6.*t12.*t15.*u1;
t19 = t5.*t6.*t12.*t15.*u1;
Gamma = [-t14.*(du1.*t3.*t12-t6.*t12.*t14.*u1)-du1.*t3.*t12.*t14-t3.*t12.*t15.*u1.*x12;-x12.*(t16+t19)-t14.*(t17+t18+du1.*t5.*t6.*t12)+du1.*(t2.*t3.*t12.*t15-t5.*t6.*t12.*t14)-t15.*(-du1.*t2.*t3.*t12+t2.*t6.*t12.*t14.*u1+t3.*t5.*t12.*t15.*u1);x12.*(t17-t18)-du1.*(t2.*t6.*t12.*t14+t3.*t5.*t12.*t15)-t14.*(t16-t19+du1.*t2.*t6.*t12)-t15.*(du1.*t3.*t5.*t12+t2.*t3.*t12.*t15.*u1-t5.*t6.*t12.*t14.*u1);x12];
