function E = E_fun(Ix,Iy,Iz,m,u1,x7,x8,x9)
%E_fun
%    E = E_fun(Ix,Iy,Iz,M,U1,X7,X8,X9)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Sep-2022 09:10:44

t2 = cos(x7);
t3 = cos(x8);
t4 = cos(x9);
t5 = sin(x7);
t6 = sin(x8);
t7 = sin(x9);
t8 = 1.0./Ix;
t9 = 1.0./Iy;
t10 = 1.0./m;
E = reshape([-t6.*t10,t3.*t5.*t10,t2.*t3.*t10,0.0,-t3.*t7.*t8.*t10.*u1,t8.*(t2.*t3.*t4.*t10.*u1-t5.*t6.*t7.*t10.*u1),-t8.*(t3.*t4.*t5.*t10.*u1+t2.*t6.*t7.*t10.*u1),0.0,-t3.*t4.*t9.*t10.*u1,-t9.*(t2.*t3.*t7.*t10.*u1+t4.*t5.*t6.*t10.*u1),-t9.*(t2.*t4.*t6.*t10.*u1-t3.*t5.*t7.*t10.*u1),0.0,0.0,0.0,0.0,1.0./Iz],[4,4]);
